# !/usr/bin/env python
# (c) Scott Cagno, 2013 All rights reserved
# License: https://sites.google.com/site/bsdc3license

vim={
	"LEFT"						:	[('type', 'h')],
	"DOWN"						:	[('type', 'j')],
	"UP"						:	[('type', 'k')],
	"RIGHT"						:	[('type', 'l')],
	"LINE"						:	[('type', 'G')],
	"NEXT"						:	[('type', 'n')],
	"PREVIOUS"					:	[('type', 'N')],
	"BACK"						:	[('type', 'b')],
	"BACK-WORD"					:	[('type', 'B')],
	"END"						:	[('type', 'e')],
	"END-WORD"					:	[('type', 'E')],
	"COLUMN"					:	[('type', '|')],
	"START-OF-LINE"				:	[('type', '^')],
	"END-OF-LINE"				:	[('type', '$')],
	"AGAIN"						:	[('type', ';')],
	"REPEATE"					:	[('type', '.')],
	"START-SENTENCE"			:	[('type', '(')],
	"END-SENTENCE"				:	[('type', ')')],
	"START-PARAGRAPH"			:	[('type', '{')],
	"END-PARAGRAPH"				:	[('type', '}')],
	"START-OF-NEXT-SECTION"		:	[('type', ']]')],
	"START-OF-PREVIOUS-SECTION"	:	[('type', '[[')],
	"END-OF-NEXT-SECTION"		:	[('type', '][')],
	"END-OF-PREVIOUS-SECTION"	:	[('type', '[]')],
	"MATCHING"					:	[('type', '%')],
	"DOWN-LINE"					:	[('type', '+')],
	"UP-LINE"					:	[('type', '-')],
	"FIRST-CHARACTER"			:	[('type', '_')],
	"HIGHEST"					:	[('type', 'H')],
	"MIDDLE"					:	[('type', 'M')],
	"LOWEST"					:	[('type', 'L')],
	"START-OF-FILE"				:	[('type', 'gg')],
	"END-OF-FILE"				:	[('type', 'G')],

	"JUMP-TO-MARK"				:	[('type', "'")],
	"FIND"						:	[('type', 'f')],
	"FIND-REVERSED"				:	[('type', 'F')],
	"TILL"						:	[('type', 't')],
	"TILL-REVERSED"				:	[('type', 'T')],
	"SEARCH"					:	[('type', '/')],
	"SEARCH-REVERSED"			:	[('type', '?')],
	"WORD"						:	[('type', 'w')],
	"BIG-WORD"					:	[('type', 'W')],

	"CHANGE"					:	[('type', 'c')],
	"DELETE"					:	[('type', 'd')],
	"DELETE-CHAR"				:	[('type', 'x')],
	"DELETE-LINE"				:	[('type', 'dd')],
	"INDENT"					:	[('type', '>')],
	"UNINDENT"					:	[('type', '<')],
	"JOIN"						:	[('type', 'J')],
	"FORMAT"					:	[('type', '=')],
	"FORMAT-LINE"				:	[('type', '==')],
	"PASTE"						:	[('type', 'p')],
	"UNDO"						:	[('type', 'u')],
	"UNDO-LINE"					:	[('type', 'U')],
	"REDO"						:	[('key', 'ctrl+r')],
	"YANK"						:	[('type', 'y')],
	"YANK-LINE"					:	[('type', 'Y')],
	"INNER"						:	[('type', 'i')],
	"AROUND"					:	[('type', 'a')],
	
	"AFTER"						:	[('type', 'a')],
	"AFTER-LINE"				:	[('type', 'A')],
	"INSERT"					:	[('type', 'i')],
	"INSERT-BEFORE-LINE"		:	[('type', 'I')],
	"OPEN-BELOW"				:	[('type', 'o')],
	"OPEN-ABOVE"				:	[('type', 'O')],
	"SCROLL-TOP"				:	[('type', 'zt')],
	"SCROLL-BOTTOM"				:	[('type', 'zb')],
	"SCROLL-START"				:	[('type', 'zs')],
	"SCROLL-END"				:	[('type', 'ze')],
	"INDENT-LINE"				:	[('type', '>>')],
	"UNINDENT-LINE"				:	[('type', '<<')],
	"TOGGLE-CASE"				:	[('type', '~')],

	"ESCAPE"					:	[('key', 'Escape')],

	"INSERT"					:	[('type', 'i')],
	"SELECT"					:	[('type', 'v')],
	"SELECT-BLOCK"				:	[('key', 'ctrl+v')],
	"VISUAL"					:	[('type', 'v')],
	"VISUAL-BLOCK"				:	[('key', 'ctrl+v')],

	"RECORD-MACRO"				:	[('type', 'qq')],
	"STOP-RECORDING"			:	[('type', 'q')],
	"PLAY-MACRO"				:	[('type', '@q')],
	"PLAY-AGAIN"				:	[('type', '@@')],

	"COMMAND"					:	[('type', ':')],

	"EDIT"						:	[('type', ':e ')],
	"FORCE-EDIT"				:	[('type', ':e! ')],
	"QUIT"						:	[('type', ':q')],
	"FORCE-QUIT"				:	[('type', ':q!')],
	"WRITE"						:	[('type', ':w')],
	"FORCE-WRITE"				:	[('type', ':w!')],
	"WRITE-QUIT"				:	[('type', ':wq')],
	"FORCE-WRITE-QUIT"			:	[('type', ':wq!')],
	"LIST-BUFFERS"				:	[('type', ':ls')],
	"BUFFER"					:	[('type', ':buf ')],
	"CLOSE-BUFFER"				:	[('type', ':bw')],

	"FIND-AND-REPLACE"			:	[('type', ':%s/')],
	"WITH"						:	[('type', '/')],
	"GLOBALLY"					:	[('type', '/g')]
}

shell={
	"YEP"			:	[('key', 'Return')],
	"TACK"			:	[('type', '-')],
	"L-S"			:	[('type', 'ls ')],
	"C-D"			:	[('type', 'cd ')],
	"TOUCH"			:	[('type', 'touch ')],
	"FILE"			:	[('type', 'file ')],
	"MAN"			:	[('type', 'man ')],
	"GREP"			:	[('type', 'grep ')],
	"TRIM"			:	[('type', 'tr ')],
	"SED"			:	[('type', 'sed ')],
	"AWK"			:	[('type', 'awk ')],
	"PIPE"			:	[('type', ' | ')],
	"LESS"			:	[('type', 'less')],
	"P-W-D"			:	[('type', 'pwd'), ('key', 'Return')],
	"P-S"			:	[('type', 'ps'), ('key', 'Return')],
	"TOP"			:	[('type', 'top'), ('key', 'Return')],
	"H-TOP"			:	[('type', 'top'), ('key', 'Return')],
	"DATE"			:	[('type', 'date'), ('key', 'Return')],
	"DONE"			:	[('type', 'q')]
}

base={
	"DICTATE"		:	None,
	"STOP-V-C-S"	:	None,
	"V-C-S"			:	None,
	"EDITOR"		:	None,
	"SHELL"			:	None
}

common={
	"TILDA"			:	[('type', '~')],
	"BANG"			:	[('type', '!')],
	"AT"			:	[('type', '@')],
	"HASH"			:	[('type', '#')],
	"DOLLAR"		:	[('type', '$')],
	"PERCENT"		:	[('type', '%')],
	"CARET"			:	[('type', '^')],
	"AMPERSAND"		:	[('type', '&')],
	"STAR"			:	[('type', '*')],
	"UNDERSCORE"	:	[('type', '_')],
	"DOT"			:	[('type', '.')],
	"COMMA"			:	[('type', ',')],
	"SEMI-COLIN"	:	[('type', ';')],
	"COLIN"			:	[('type', ':')],
	"SPACE"			:	[('type', ' ')],
	
	"PARENS"		:	[('type', '()'), ('key', 'Left')],
	"LEFT-PAREN"	:	[('type', '(')],
	"RIGHT-PAREN"	:	[('type', ')')],
	"BRACKETS"		:	[('type', '[]'), ('key', 'Left')],
	"LEFT-BRACKET"	:	[('type', '[')],
	"RIGHT-BRACKET"	:	[('type', ']')],
	"BRACES"		:	[('type', '{}'), ('key', 'Left')],
	"LEFT-BRACE"	:	[('type', '{')],
	"RIGHT-BRACE"	:	[('type', '}')],

	"RETURN"		:	[('key', 'Return')],
	"BACKSPACE"		:	[('key', 'Backspace')],
	"CAPS-LOCK"		:	[('key', 'Caps_Lock')],
	
	"ZERO"			:	[('type', '0')],
	"ONE"			:	[('type', '1')],
	"TWO"			:	[('type', '2')],
	"THREE"			:	[('type', '3')],
	"FOUR"			:	[('type', '4')],
	"FIVE"			:	[('type', '5')],
	"SIX"			:	[('type', '6')],
	"SEVEN"			:	[('type', '7')],
	"EIGHT"			:	[('type', '8')],
	"NINE"			:	[('type', '9')],

	"ALPHA"			:	[('type', 'a')],
	"BRAVO"			:	[('type', 'b')],
	"CHARLIE"		:	[('type', 'c')],
	"DELTA"			:	[('type', 'd')],
	"ECHO"			:	[('type', 'e')],
	"FOXTROT"		:	[('type', 'f')],
	"GOLF"			:	[('type', 'g')],
	"HOTEL"			:	[('type', 'h')],
	"INDIA"			:	[('type', 'i')],
	"JULIETTE"		:	[('type', 'j')],
	"KILO"			:	[('type', 'k')],
	"LIMA"			:	[('type', 'l')],
	"MIKE"			:	[('type', 'm')],
	"NOVEMBER"		:	[('type', 'n')],
	"OSCAR"			:	[('type', 'o')],
	"PAPA"			:	[('type', 'p')],
	"QUEBEC"		:	[('type', 'q')],
	"ROMEO"			:	[('type', 'r')],
	"SIERRA"		:	[('type', 's')],
	"TANGO"			:	[('type', 't')],
	"UNIFORM"		:	[('type', 'u')],
	"VICTOR"		:	[('type', 'v')],
	"WHISKEY"		:	[('type', 'w')],
	"X-RAY"			:	[('type', 'x')],
	"YANKEE"		:	[('type', 'y')],
	"ZULU"			:	[('type', 'z')],

	"CAP-ALPHA"		:	[('type', 'A')],
	"CAP-BRAVO"		:	[('type', 'B')],
	"CAP-CHARLIE"	:	[('type', 'C')],
	"CAP-DELTA"		:	[('type', 'D')],
	"CAP-ECHO"		:	[('type', 'E')],
	"CAP-FOXTROT"	:	[('type', 'F')],
	"CAP-GOLF"		:	[('type', 'G')],
	"CAP-HOTEL"		:	[('type', 'H')],
	"CAP-INDIA"		:	[('type', 'I')],
	"CAP-JULIETTE"	:	[('type', 'J')],
	"CAP-KILO"		:	[('type', 'K')],
	"CAP-LIMA"		:	[('type', 'L')],
	"CAP-MIKE"		:	[('type', 'M')],
	"CAP-NOVEMBER"	:	[('type', 'N')],
	"CAP-OSCAR"		:	[('type', 'O')],
	"CAP-PAPA"		:	[('type', 'P')],
	"CAP-QUEBEC"	:	[('type', 'Q')],
	"CAP-ROMEO"		:	[('type', 'R')],
	"CAP-SIERRA"	:	[('type', 'S')],
	"CAP-TANGO"		:	[('type', 'T')],
	"CAP-UNIFORM"	:	[('type', 'U')],
	"CAP-VICTOR"	:	[('type', 'V')],
	"CAP-WHISKEY"	:	[('type', 'W')],
	"CAP-X-RAY"		:	[('type', 'X')],
	"CAP-YANKEE"	:	[('type', 'Y')],
	"CAP-ZULU"		:	[('type', 'Z')]
}
